.gitignore

These are the directories which are created if you install directly from the repo.  Git should ignore them.

Add python dist files to .gitignore.

---

pushbullet/channel.py
pushbullet/invalid_key_error.py
pushbullet/pushbullet.py
readme.rst

Added additional class `Channel`, which enables sending push messages to channels created by the current user. The channels which have been created are accessible through a new attribute `channels` of the `PushBullet` class. The API of the new `Channel` class is identical to existing classes (such as `Device`). I've updated the Readme with an example.

Send pushes to channels

---

readme.rst

Under "Pushing a text note", the pb.push_note() example has a trailing fullstop outside the inverted commas which is obviously invalid syntax.

Correct typo for push_note() example in readme

---

requirements.txt
setup.py

pip.req.parse_requirements is not considered part of the public
pip API by the pip developers and hence should never be used
as such. Its signature can change at any given moment, making
installations depending on it just break.
This patch moves the actual requirement specification over into
setup.py and modifies requirements.txt to only contain a reference
to the local package, in compliance with the suggested usage
pattern for setup.py vs requirements.txt.
See also:
* http://stackoverflow.com/a/22649833/2028598
* https://caremad.io/2013/07/setup-vs-requirement/
Solves #36

Fix: Do not use the non-public parse_requirements

---

pushbullet/filetype.py

For some reason libmagic return bytes instead of a string in Python 3, which can't be serialised to json

Fix libmagic issue with Python 3

---

pushbullet/pushbullet.py

A bad response isn't necessarily a 401 response, use the requests library response check instead of hardcoding 401 to cover these issues.

Fix 403 response codes

---

example/listener_example.py

set file as executable as well

Update listener example to match current API

---

example/mirror_example.py
example/sample_config.json

There were a few problems with the mirror example
1. Creating a device with call to PushBullet.new_device() does not return a (boolean,device) tuple. It will throw and error if it fails. Using a try catch with informative error messages should help the user. Re-raising the error will also stop the program, since it should not run without a valid device.
2. The default "last_push" is 0. On an account with many pushes, this could cause a rate limit restriction from pushbullet.com just by running the mirror a few times. setting it to time.time() will restrict mirror to new pushes.
3. In check_pushes() there are some errors when the push in pushes is not actually a push dictionary. Adding a check for isinstance(push,dict) will prevent this error.
4. dump_config does not write out the …

Fixes for mirror_example

---

pushbullet/pushbullet.py

Editing a device using the `edit_device()` method without a nickname given would result in the nickname being deleted from the device. This is due to the default `nickname=None` value. This also then causes a 'tuple index out of range' error if the device list is called upon using `pb.devices`.

Fix edit_device method to keep nickname

---

pushbullet/pushbullet.py

Currently to retrieve a specific device, the user needs to know the index of the `Device` in the device list. This requires either to print devices first using `pb.devices` or to retrieve all devices and use a loop.
As the pushbullet.py package retrieves all devices on initial connection, it is easier to provide a helper method for the end user.

Add new method to get device by nickname

---

pushbullet/device.py
pushbullet/pushbullet.py
tests/test_devices.py

The attributes on the `Device` were from an old version of the pushbullet API. Deprecated attributes have been removed and latest ones have been added.
The `new_device()` function has been updated to support some of these new attributes on device creation.

Edited Device attributes and adjusted new_device() function

---

pushbullet/pushbullet.py
readme.rst

As per issue #34 - Pushbullet allows pushing direct to a channel. I have added a shortcut method to retrieve channel by channel_tag which can be used as a shortcut in `pb.push_note(channel=pb.get_channel())` if need be.
Edited readme as well to describe the new functions.

Add new function to get_channel and ability to push direct to channel

---

pushbullet/channel.py
pushbullet/device.py
pushbullet/pushbullet.py
tests/test_channels.py
tests/test_devices.py

https://docs.pushbullet.com/#changelog
January 28, 2015
• Removed address and list pushes which have been deprecated for forever.
#86

Removed address and list pushes which have been deprecated for forever.

---

pushbullet/channel.py
pushbullet/device.py
pushbullet/pushbullet.py
tests/test_channels.py
tests/test_devices.py

#52 added the title parameter to `pushbullet.py`, but the channel and device objects didn't have this parameter in `send_file`.

Add title parameter for send_file in device and channel objects. Improves #52

---

.travis.yml
pushbullet/pushbullet.py
tests/test_e2e.py

This PR adds decryption support to the PB base class. It is based on both the Cryptography examples on AES-GCM decryption and Pushbullet's API examples. I tried to make it work as similarly as your encryption method.
I have been using it this afternoon and have [this screencast](https://gfycat.com/SoreFrigidCaracal) showing it in action in my `pushbullet.py`-based PB client.

Add decryption support

---

pushbullet/listener.py

This PR adds basic support for handling errors for `websockets-client` listener. Without it no exception was raised on, say, KeyboardInterrupt and I wanted to handle them in order to clean up.

Add on_error callback support

---

MANIFEST.in

Hi,
It would be really nice if you could include tests and examples in the PyPI tarballs as we at Gentoo usually get the package source there.

Include tests and examples in source distributions

---

pushbullet/filetype.py

Got here from pushbullet-cli. We are having problems with the current approach. I managed to make it work by catching the possible exception

Better handling for python3 missing `decode`

---

pushbullet/listener.py
setup.py

As of version 0.53.0 of websocket-client (websocket-client/websocket-client@efcf31b), the `ws` parameter is no longer needed.

Fixed missing 1 required positional argument: 'ws'

---

readme.rst

The pypi downloads shield no longer works so might as well remove it. https://github.com/badges/shields/issues/716
Also updated the project's pypi url.

Remove download shield and fix pypi link

---

pushbullet/pushbullet.py

I know it's a silly little change. Though, surely it is _better_ to use the literal syntax?

Use curly brace literal instead of dict function

---

pushbullet/filetype.py

There are several magic libraries, and notably unix `file`
does not include a `from_buffer`.

filetype: Import magic.from_buffer

---

.gitignore
pushbullet/channel.py
pushbullet/device.py
pushbullet/errors.py
pushbullet/filetype.py
pushbullet/pushbullet.py

What does this PR do?
- Response no longer fails if rate limit headers are missing
- Rate limit info is now under `rate_limit` property
- Removed deprecated `push_address` and `push_list` methods 
- Adds a `gitignore` from GitHub

Fix file type detection, rate limit headers

---

readme.md

Previously, clicking on these images from the Github project page would
open the images themselves in a new tab. This commit adds a link to the
PyPI project page from the PyPI badge, and a relative link to the
LICENSE file in this repository from the license badge.

Add links for the PyPI and License badges
